# Generated by Django 5.2.17 on 2026-10-01 20:08

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                ("name", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "role",
                    models.CharField(
                        choices=[("admin", "Admin"), ("member", "Membro")],
                        default="member",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("email"), name="user_email_ci_unique"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("role__in", ["admin", "member"])),
                        name="user_valid_role",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="LoginBucket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("kind", models.CharField(max_length=10)),
                ("key", models.CharField(max_length=64)),
                ("identity_key", models.CharField(db_index=True, max_length=64, null=True)),
                ("network_key", models.CharField(db_index=True, max_length=64, null=True)),
                ("window_start", models.DateTimeField()),
                ("count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "indexes": [models.Index(fields=["window_start"], name="login_bucket_window")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("kind", "key", "window_start"), name="login_bucket_unique"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("kind__in", ["ip", "pair", "identity"])),
                        name="login_bucket_kind",
                    ),
                ],
            },
        ),
    ]
