# Generated by Django 5.2.17 on 2026-10-01 20:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("description", models.CharField(blank=True, default="", max_length=2000)),
                ("capacity", models.PositiveSmallIntegerField()),
                ("location", models.CharField(max_length=200)),
                ("resources", models.JSONField(default=list)),
                ("status", models.CharField(db_index=True, default="active", max_length=10)),
                ("blocked_reason", models.CharField(blank=True, default="", max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("capacity__gte", 1), ("capacity__lte", 100)),
                        name="room_capacity",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ["active", "blocked", "inactive"])),
                        name="room_status",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("status", "blocked"),
                                models.Q(("blocked_reason", ""), _negated=True),
                            ),
                            models.Q(
                                ("blocked_reason", ""), ("status__in", ["active", "inactive"])
                            ),
                            _connector="OR",
                        ),
                        name="room_blocked_reason",
                    ),
                ],
            },
        ),
    ]
