import type { Page, TestInfo } from '@playwright/test';
import { test, expect, login, unique, futureInterval, localDate, localTime, assertA11y, assertNoOverflow, capture, assertSuccessFocus, type Room, type Reservation } from './support.js';

async function transition(page: Page, room: Room, action: string, label: string, affected = 1, info?: TestInfo): Promise<Room> {
  const trigger = page.getByRole('button', { name: `${label} ${room.name}`, exact: true });
  await trigger.focus();
  await page.keyboard.press('Enter');
  const dialog = page.getByRole('dialog');
  await expect(dialog.getByRole('button', { name: 'Manter estado atual', exact: true })).toBeFocused();
  if (info) await capture(page, info, `admin-${action}-initial-focus`, false);
  await page.keyboard.press('Escape');
  await expect(dialog).not.toBeVisible();
  await page.waitForLoadState('networkidle');
  await expect(trigger).toBeFocused();
  if (info) await capture(page, info, `admin-${action}-escape-restored-focus`, false);
  await page.keyboard.press('Enter');
  await expect(dialog.getByRole('button', { name: 'Manter estado atual', exact: true })).toBeFocused();
  await expect(dialog).toContainText(`${affected} reservas confirmadas ainda não encerradas`);
  if (action === 'block') await dialog.getByRole('textbox', { name: 'Motivo do bloqueio', exact: true }).fill('Manutenção planejada QA');
  const response = page.waitForResponse(r => r.url().endsWith(`/api/rooms/${room.id}/${action}`));
  await dialog.getByRole('button', { name: `${label} sala`, exact: true }).click();
  const result = await response;
  expect(result.status()).toBe(200);
  const data = await result.json() as Room & { affected_reservations_count: number };
  expect(data.affected_reservations_count).toBe(affected);
  await expect(dialog).not.toBeVisible();
  await assertSuccessFocus(page, /Estado atualizado/);
  await expect(page.locator(':focus')).toContainText(`${affected} reservas confirmadas ainda não encerradas afetadas`);
  if (info) await capture(page, info, `admin-${action}-success-focus`, false);
  return data;
}

test('admin cria/edita sala, bloqueia/desbloqueia/inativa, trata reserva alheia e preserva histórico', async ({ page, memberApi }, info) => {
  const name = unique('Admin QA');
  await login(page, 'admin');
  await page.goto('/admin/rooms');
  await page.getByRole('button', { name: '+ Nova sala', exact: true }).click();
  const editor = page.getByRole('dialog', { name: 'Nova sala', exact: true });
  await editor.getByLabel('Nome da sala', { exact: true }).fill(name);
  await editor.getByLabel('Localização', { exact: true }).fill('Andar administrativo QA');
  await editor.getByLabel('Capacidade', { exact: true }).fill('12');
  await editor.getByRole('textbox', { name: 'Descrição da sala', exact: true }).fill('Descrição original criada pela interface');
  await editor.getByLabel('Projetor', { exact: true }).check();
  await assertA11y(page, info, 'room-editor');
  const creation = page.waitForResponse(r => r.url().endsWith('/api/rooms') && r.request().method() === 'POST');
  await editor.getByRole('button', { name: 'Criar sala', exact: true }).click();
  const createdResponse = await creation;
  expect(createdResponse.status()).toBe(201);
  let room = await createdResponse.json() as Room;
  await expect(editor).not.toBeVisible();
  await assertSuccessFocus(page, /Sala salva/);
  await page.getByLabel('Buscar salas', { exact: true }).fill(name);
  await page.getByRole('button', { name: 'Filtrar salas', exact: true }).click();
  const editTrigger = page.getByRole('button', { name: `Editar ${name}`, exact: true });
  await editTrigger.focus();
  await page.keyboard.press('Enter');
  const edit = page.getByRole('dialog', { name: 'Editar sala', exact: true });
  await expect(edit.getByLabel('Nome da sala', { exact: true })).toHaveValue(name);
  await page.keyboard.press('Escape');
  await expect(edit).not.toBeVisible();
  await page.waitForLoadState('networkidle');
  await expect(editTrigger).toBeFocused();
  await capture(page, info, 'admin-editor-escape-restored-focus', false);
  await page.keyboard.press('Enter');
  await expect(edit).toBeVisible();
  await edit.getByLabel('Capacidade', { exact: true }).fill('10');
  await edit.getByRole('textbox', { name: 'Descrição da sala', exact: true }).fill('Descrição atualizada pela interface');
  await edit.getByLabel('Videoconferência', { exact: true }).check();
  const update = page.waitForResponse(r => r.url().endsWith(`/api/rooms/${room.id}`) && r.request().method() === 'PATCH');
  await edit.getByRole('button', { name: 'Salvar alterações', exact: true }).click();
  expect((await update).status()).toBe(200);
  await expect(edit).not.toBeVisible();
  await assertSuccessFocus(page, /Sala salva/);
  await capture(page, info, 'admin-editor-success-focus', false);
  room = await memberApi.get<Room>(`/rooms/${room.id}`);
  expect(room.capacity).toBe(10);
  const reservation = await memberApi.createReservation(room, unique('Reserva do membro para tratamento'), futureInterval(5), 4);
  room = await transition(page, room, 'block', 'Bloquear', 1, info);
  expect(room.status).toBe('blocked');
  let persisted = await memberApi.get<Reservation>(`/reservations/${reservation.id}`);
  expect(persisted.status).toBe('confirmed');
  expect(persisted.room.status).toBe('blocked');
  await capture(page, info, 'admin-blocked-room');
  room = await transition(page, room, 'unblock', 'Desbloquear');
  expect(room.status).toBe('active');
  expect(room.blocked_reason).toBe('');
  room = await transition(page, room, 'deactivate', 'Inativar');
  expect(room.status).toBe('inactive');
  await memberApi.get(`/rooms/${room.id}`, 403);
  persisted = await memberApi.get<Reservation>(`/reservations/${reservation.id}`);
  expect(persisted.status).toBe('confirmed');
  expect(persisted.room.status).toBe('inactive');
  await assertNoOverflow(page);
  await capture(page, info, 'admin-inactive-history-preserved');
  await page.getByRole('link', { name: 'Tratar reservas afetadas', exact: true }).click();
  await page.getByRole('button', { name: `Cancelar ${reservation.title}`, exact: true }).click();
  await page.getByRole('dialog').getByRole('button', { name: 'Cancelar reserva', exact: true }).click();
  await expect(page.getByRole('dialog')).not.toBeVisible();
  await assertSuccessFocus(page, /Reserva cancelada/);
  await page.getByRole('button', { name: 'Canceladas', exact: true }).click();
  await expect(page.getByRole('link', { name: reservation.title, exact: true })).toBeVisible();
  expect((await memberApi.get<Reservation>(`/reservations/${reservation.id}`)).status).toBe('cancelled');
  await capture(page, info, 'admin-cancelled-other-owner');
  await page.goto(`/admin/rooms?search=${encodeURIComponent(name)}`);
  room = await transition(page, room, 'reactivate', 'Reativar', 0);
  expect(room.status).toBe('active');
});

type AuditEvent = { id: number; type: string; actor: { id: number; name: string } | null; result: string; resource_id: string; count: number; first_at: string; last_at: string; metadata: Record<string, unknown> };
type AuditPage = { results: AuditEvent[]; next_cursor: string | null; has_more: boolean };

test('auditoria combina filtros e pagina eventos reais sem duplicar IDs', async ({ page, adminApi }, info) => {
  const since = new Date(Date.now() - 60_000).toISOString();
  const until = new Date(Date.now() + 3_600_000).toISOString();
  const room = await adminApi.createRoom(unique('Auditoria QA'));
  // More than the UI page size makes the pagination assertion independent of seed data.
  for (let index = 0; index < 21; index++) await adminApi.write(`/rooms/${room.id}`, { description: `Texto livre privado QA ${index}` }, 200, 'PATCH');
  const { user } = await adminApi.get<{ user: { id: number } }>('/session/me');
  await login(page, 'admin');
  await page.goto('/admin/audit');
  await page.getByRole('combobox', { name: 'Tipo de evento', exact: true }).selectOption('room.updated');
  await page.getByLabel('ID do ator', { exact: true }).fill(String(user.id));
  await page.getByRole('combobox', { name: 'Resultado', exact: true }).selectOption('success');
  await page.getByLabel('Auditoria: a partir de', { exact: true }).fill(`${localDate(since)}T${localTime(since)}`);
  await page.getByLabel('Auditoria: até', { exact: true }).fill(`${localDate(until)}T${localTime(until)}`);
  const firstResponse = page.waitForResponse(r => r.url().includes('/api/audit-events?') && new URL(r.url()).searchParams.get('type') === 'room.updated' && !new URL(r.url()).searchParams.get('cursor'));
  await page.getByRole('button', { name: 'Filtrar eventos', exact: true }).click();
  const response = await firstResponse;
  expect(response.status()).toBe(200);
  const first = await response.json() as AuditPage;
  expect(first.results).toHaveLength(20);
  expect(first.has_more).toBe(true);
  expect(first.results.some(event => event.resource_id === String(room.id))).toBe(true);
  for (const event of first.results) {
    expect(event.type).toBe('room.updated');
    expect(event.actor?.id).toBe(user.id);
    expect(event.result).toBe('success');
    expect(event.count).toBe(1);
  }
  expect(JSON.stringify(first)).not.toContain('Texto livre privado QA');
  expect(JSON.stringify(first)).not.toContain(room.name);
  await expect(page.getByRole('table')).toBeVisible();
  await expect(page.getByText(/a contagem cobre o grupo inteiro/i)).toBeVisible();
  await assertNoOverflow(page);
  await assertA11y(page, info, 'audit-filtered');
  await capture(page, info, 'audit-filtered');
  const nextResponse = page.waitForResponse(r => r.url().includes('/api/audit-events?') && new URL(r.url()).searchParams.get('cursor') === String(first.next_cursor));
  await page.getByRole('button', { name: 'Próximos eventos', exact: true }).click();
  const next = await nextResponse;
  expect(next.status()).toBe(200);
  const second = await next.json() as AuditPage;
  expect(second.results.length).toBeGreaterThan(0);
  expect(second.results.every(event => !first.results.some(previous => previous.id === event.id))).toBe(true);
  expect(second.results[0].id).toBeLessThan(first.results.at(-1)!.id);
  await page.reload();
  await expect(page.getByRole('combobox', { name: 'Tipo de evento', exact: true })).toHaveValue('room.updated');
  await expect(page.getByLabel('ID do ator', { exact: true })).toHaveValue(String(user.id));
  await expect(page.getByRole('combobox', { name: 'Resultado', exact: true })).toHaveValue('success');
  await expect(page.getByRole('button', { name: 'Anteriores', exact: true })).toBeEnabled();
  const previousResponse = page.waitForResponse(r => r.url().includes('/api/audit-events?') && !new URL(r.url()).searchParams.get('cursor'));
  await page.getByRole('button', { name: 'Anteriores', exact: true }).click();
  const restored = await (await previousResponse).json() as AuditPage;
  expect(restored.results.map(event => event.id)).toEqual(first.results.map(event => event.id));
  await page.goBack();
  await expect.poll(() => new URL(page.url()).searchParams.get('cursor')).toBe(String(first.next_cursor));
  await expect(page.getByRole('combobox', { name: 'Tipo de evento', exact: true })).toHaveValue('room.updated');
});
