# Generated by Django 5.2.17 on 2026-10-01 20:08

import datetime
import uuid

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.contrib.postgres.operations import BtreeGistExtension
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("rooms", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        BtreeGistExtension(),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("description", models.CharField(blank=True, default="", max_length=2000)),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                ("participants", models.PositiveSmallIntegerField()),
                ("status", models.CharField(default="confirmed", max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("cancelled_at", models.DateTimeField(null=True)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to="rooms.room",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["user", "starts_at", "id"], name="reservation_user_start"),
                    models.Index(fields=["room", "starts_at"], name="reservation_room_start"),
                    models.Index(
                        condition=models.Q(("status", "confirmed")),
                        fields=["starts_at", "ends_at"],
                        name="reservation_confirmed_time",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("participants__gte", 1), ("participants__lte", 100)),
                        name="reservation_participants",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "ends_at__gte",
                                django.db.models.expressions.CombinedExpression(
                                    models.F("starts_at"),
                                    "+",
                                    models.Value(datetime.timedelta(seconds=900)),
                                ),
                            ),
                            (
                                "ends_at__lte",
                                django.db.models.expressions.CombinedExpression(
                                    models.F("starts_at"),
                                    "+",
                                    models.Value(datetime.timedelta(seconds=28800)),
                                ),
                            ),
                        ),
                        name="reservation_duration",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("cancelled_at__isnull", True), ("status", "confirmed")),
                            models.Q(("cancelled_at__isnull", False), ("status", "cancelled")),
                            _connector="OR",
                        ),
                        name="reservation_status_cancelled",
                    ),
                    django.contrib.postgres.constraints.ExclusionConstraint(
                        condition=models.Q(("status", "confirmed")),
                        expressions=[
                            ("room", "="),
                            (
                                models.Func(
                                    "starts_at",
                                    "ends_at",
                                    models.Value("[)"),
                                    function="TSTZRANGE",
                                    output_field=django.contrib.postgres.fields.ranges.DateTimeRangeField(),
                                ),
                                "&&",
                            ),
                        ],
                        name="reservation_no_overlap",
                    ),
                ],
            },
        ),
    ]
