# Generated by Django 5.2.17 on 2026-10-01 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("type", models.CharField(max_length=40)),
                ("first_at", models.DateTimeField(db_index=True)),
                ("last_at", models.DateTimeField(db_index=True)),
                ("count", models.PositiveBigIntegerField(default=1)),
                ("resource", models.CharField(max_length=20)),
                ("resource_id", models.CharField(max_length=64, null=True)),
                ("result", models.CharField(max_length=10)),
                ("metadata", models.JSONField(default=dict)),
                ("aggregation_key", models.CharField(max_length=64, null=True, unique=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["type", "id"], name="audit_type_id"),
                    models.Index(fields=["actor", "id"], name="audit_actor_id"),
                    models.Index(fields=["result", "id"], name="audit_result_id"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("first_at__lte", models.F("last_at"))),
                        name="audit_time_order",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("count__gte", 1)), name="audit_count_positive"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("result__in", ["success", "denied"])),
                        name="audit_result",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "type__in",
                                (
                                    "login.success",
                                    "login.denied",
                                    "logout",
                                    "login.limit_unlocked",
                                    "account.provisioned",
                                    "room.created",
                                    "room.updated",
                                    "room.blocked",
                                    "room.unblocked",
                                    "room.deactivated",
                                    "room.reactivated",
                                    "reservation.created",
                                    "reservation.cancelled",
                                    "operation.denied",
                                ),
                            )
                        ),
                        name="audit_type",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "resource__in",
                                ("session", "http", "room", "reservation", "user", "login_limit"),
                            )
                        ),
                        name="audit_resource",
                    ),
                ],
            },
        ),
    ]
